const QUESTION_BANK=window.QCM||[], $=id=>document.getElementById(id), letters=['A','B','C','D'];
let S=null,choice=null,timer=null,left=0;
const store={get:k=>{try{return JSON.parse(localStorage.getItem(k))}catch{return null}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),del:k=>localStorage.removeItem(k)};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function init(){const cats=[...new Set(QUESTION_BANK.map(q=>q.category))];$('themeList').innerHTML=cats.map(c=>`<label class="theme-item"><input type="checkbox" value="${c}" checked><span>${c}</span><span class="theme-count">${QUESTION_BANK.filter(q=>q.category===c).length}</span></label>`).join('');$('resumeBtn').classList.toggle('hidden',!store.get('qcm_current_session'));renderHistory();bind();const th=store.get('qcm_theme');if(th)document.documentElement.dataset.theme=th}
function bind(){$('startBtn').onclick=start;$('resumeBtn').onclick=resume;$('validateBtn').onclick=validate;$('nextBtn').onclick=next;$('prevBtn').onclick=prev;$('quitBtn').onclick=quit;$('restartBtn').onclick=home;$('exportBtn').onclick=exportResult;$('printBtn').onclick=()=>window.print();$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=importProgress;$('themeBtn').onclick=()=>{const d=document.documentElement.dataset.theme==='dark'?'':'dark';document.documentElement.dataset.theme=d;store.set('qcm_theme',d)}}
function start(){const cats=[...document.querySelectorAll('#themeList input:checked')].map(x=>x.value);if(!cats.length)return toast('Sélectionnez au moins un chapitre.');let qs=QUESTION_BANK.filter(q=>cats.includes(q.category)&&($('difficultySelect').value==='all'||q.difficulty===$('difficultySelect').value));if($('shuffleToggle').checked)qs=shuffle(qs);const n=$('countSelect').value==='all'?qs.length:+$('countSelect').value;qs=qs.slice(0,n).map(q=>{q=JSON.parse(JSON.stringify(q));if($('shuffleAnswersToggle').checked){const z=q.options.map((v,i)=>({v,i}));const m=shuffle(z);q.options=m.map(x=>x.v);q.correct=m.findIndex(x=>x.i===q.correct)}return q});S={questions:qs,answers:Array(qs.length).fill(null),index:0,mode:$('modeSelect').value,timer:+$('timerSelect').value,startedAt:new Date().toISOString(),completed:false};store.set('qcm_current_session',S);showQuiz()}
function resume(){S=store.get('qcm_current_session');if(!S)return toast('Aucune session sauvegardée.');showQuiz()}
function showQuiz(){$('homeView').classList.add('hidden');$('resultView').classList.add('hidden');$('quizView').classList.remove('hidden');renderQ()}
function renderQ(){clearInterval(timer);choice=S.answers[S.index];const q=S.questions[S.index];$('categoryBadge').textContent=q.category;$('difficultyBadge').textContent=q.difficulty;$('modeBadge').textContent=S.mode==='training'?'Entraînement':'Examen';$('qNumber').textContent=`Question ${S.index+1} sur ${S.questions.length}`;$('questionText').textContent=q.question;$('progressBar').style.width=`${(S.index/S.questions.length)*100}%`;$('scoreLive').textContent=`Répondues : ${S.answers.filter(x=>x!==null).length}/${S.questions.length}`;$('explanationBox').classList.add('hidden');$('nextBtn').classList.add('hidden');$('validateBtn').classList.remove('hidden');$('validateBtn').disabled=choice===null;$('prevBtn').classList.toggle('hidden',S.index===0);$('optionsBox').innerHTML=q.options.map((o,i)=>`<button class="option ${choice===i?'selected':''}" data-i="${i}"><span class="letter">${letters[i]}</span><span>${o}</span></button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>{choice=+b.dataset.i;document.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('validateBtn').disabled=false});if(S.timer){left=S.timer;$('timerText').textContent=`⏱ ${left}s`;timer=setInterval(()=>{left--;$('timerText').textContent=`⏱ ${left}s`;if(left<=0){clearInterval(timer);if(choice===null)choice=-1;validate()}},1000)}else $('timerText').textContent=''}
function validate(){clearInterval(timer);S.answers[S.index]=choice;store.set('qcm_current_session',S);if(S.mode==='training'){const q=S.questions[S.index];document.querySelectorAll('.option').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');if(i===choice&&i!==q.correct)b.classList.add('wrong')});const ok=choice===q.correct,e=$('explanationBox');e.className=`explanation ${ok?'good':'bad'}`;e.innerHTML=`<h4>${ok?'Bonne réponse':'Réponse incorrecte'}</h4><p>${q.explanation}</p><span class="source">${q.source}</span>`;e.classList.remove('hidden');$('validateBtn').classList.add('hidden');$('nextBtn').classList.remove('hidden');$('nextBtn').textContent=S.index===S.questions.length-1?'Voir les résultats':'Suivant'}else next()}
function next(){if(S.index<S.questions.length-1){S.index++;store.set('qcm_current_session',S);renderQ()}else finish()}
function prev(){if(S.index>0){S.index--;store.set('qcm_current_session',S);renderQ()}}
function quit(){clearInterval(timer);store.set('qcm_current_session',S);home();toast('Session sauvegardée.')}
function finish(){clearInterval(timer);S.completed=true;S.result=score();store.del('qcm_current_session');const h=store.get('qcm_history')||[];h.unshift({date:new Date().toISOString(),score:S.result.correct,total:S.questions.length,pct:S.result.pct});store.set('qcm_history',h.slice(0,5));showResults()}
function score(){let correct=0;const by={};S.questions.forEach((q,i)=>{const ok=S.answers[i]===q.correct;if(ok)correct++;by[q.category]??={c:0,t:0};by[q.category].t++;if(ok)by[q.category].c++});return{correct,pct:Math.round(correct*100/S.questions.length),by}}
function showResults(){const r=S.result||score();$('quizView').classList.add('hidden');$('homeView').classList.add('hidden');$('resultView').classList.remove('hidden');$('finalPercent').textContent=`${r.pct} %`;$('finalScore').textContent=`${r.correct} / ${S.questions.length}`;$('scoreRing').style.setProperty('--pct',`${r.pct}%`);$('resultTitle').textContent=r.pct>=80?'Excellent travail':r.pct>=60?'Bon résultat':'Révision à poursuivre';$('resultSubtitle').textContent='Consultez la correction détaillée ci-dessous.';$('breakdownBox').innerHTML=Object.entries(r.by).map(([k,v])=>`<div class="break-row"><div><div class="break-name">${k}</div><div class="mini-bar"><i style="width:${Math.round(v.c*100/v.t)}%"></i></div></div><b>${v.c}/${v.t}</b></div>`).join('');$('reviewBox').innerHTML=S.questions.map((q,i)=>{const ok=S.answers[i]===q.correct;return`<details><summary>${ok?'✓':'✗'} ${i+1}. ${q.question}</summary><div class="review-content"><p><b>Votre réponse :</b> ${S.answers[i]>=0?q.options[S.answers[i]]:'Aucune'}</p><p><b>Bonne réponse :</b> ${q.options[q.correct]}</p><p>${q.explanation}</p><span class="source">${q.source}</span></div></details>`}).join('')}
function home(){$('quizView').classList.add('hidden');$('resultView').classList.add('hidden');$('homeView').classList.remove('hidden');$('resumeBtn').classList.toggle('hidden',!store.get('qcm_current_session'));renderHistory();scrollTo(0,0)}
function renderHistory(){const h=store.get('qcm_history')||[];$('historyList').innerHTML=h.length?h.map(x=>`<div class="history-item"><span>${new Date(x.date).toLocaleDateString('fr-FR')}</span><b>${x.score}/${x.total} — ${x.pct}%</b></div>`).join(''):'<p style="color:var(--muted)">Aucun résultat enregistré.</p>'}
function exportResult(){const blob=new Blob([JSON.stringify({session:S},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='resultat_qcm_bacteriologie.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importProgress(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);S=d.session||d;if(S.completed)showResults();else{store.set('qcm_current_session',S);home();toast('Progression importée.')}}catch{toast('Fichier invalide.')}};r.readAsText(f)}
init();